blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/bulletproof-sh/.github/discussions
    about: Ask a question or start a conversation (not a bug or feature request)
